[ip]
name = "amp"
summary = "an amplified standard library"
version = "2.0.0" # dev
source = "https://github.com/hyperspace-labs/amp/archive/refs/tags/2.0.0.zip"

# See more keys and their definitions at https://cdotrus.github.io/orbit/reference/manifest.html

[dependencies]
