[ip]
name = "amp"
library = "nano"
version = "1.0.0"
description = "Standard types and functions"
source = "https://github.com/hyperspace-labs/nanoamp/archive/refs/tags/{{orbit.ip.version}}.zip"
public = ["/src"]

# See more keys and their definitions at https://chaseruskin.github.io/orbit/reference/manifest.html

[dependencies]
amp = "1.0"