[ip]
name = "amp"
summary = "an amplified standard library"
version = "1.1.0" # dev
source = "https://github.com/hyperspace-labs/amp/archive/refs/tags/1.1.0.zip"

# See more keys and their definitions at https://cdotrus.github.io/orbit/reference/manifest.html

[dependencies]
