name: test
on:
  push:

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    container:
        image: cdotrus/groovy-guitar
    steps:
      - name: Fetch repository
        uses: actions/checkout@v3

      - name: Log all tool versions
        run: |
          orbit --version  
          python --version
          ghdl --version
        
      - name: Configure orbit profile
        run: |
          git clone https://github.com/cdotrus/orbit-profile.git "$(orbit env ORBIT_HOME)/profiles/cdotrus"
          pip install -r "$(orbit env ORBIT_HOME)/profiles/cdotrus/requirements.txt"
          orbit config --append include="profiles/cdotrus/config.toml"

      - name: Verify prelude package has latest changes
        run: |
          python ./scripts/prelude.py

      - name: Perform static analysis
        run: |
          orbit plan --clean --plugin gsim --all
          orbit b -- --lint --std=93
          orbit b -- --lint --std=02
          orbit b -- --lint --std=08

      - name: Test types package
        run: |
          orbit plan --clean --plugin gsim --bench types_tb
          orbit b -- --std=93
          orbit b -- --std=02
          orbit b -- --std=08

      - name: Test math package
        run: |
          orbit plan --clean --plugin gsim --bench math_tb
          orbit b -- --std=93
          orbit b -- --std=02
          orbit b -- --std=08

      - name: Test manip package
        run: |
          orbit plan --clean --plugin gsim --bench manip_tb
          orbit b -- --std=93
          orbit b -- --std=02
          orbit b -- --std=08

      - name: Test dims package
        run: |
          orbit plan --clean --plugin gsim --bench dims_tb
          orbit b -- --std=93
          orbit b -- --std=02
          orbit b -- --std=08

      - name: Test cast package
        run: |
          orbit plan --clean --plugin gsim --bench cast_tb
          orbit b -- --std=93
          orbit b -- --std=02
          orbit b -- --std=08