name: Test
on:
  push:

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    container:
        image: cdotrus/groovy-guitar
    steps:
      - name: Fetch repository
        uses: actions/checkout@v3

      - name: Log all tool versions
        run: |
          orbit --version  
          python --version
          ghdl --version
        
      - name: Configure orbit profile
        run: |
          git clone https://github.com/hyperspace-labs/orbit-profile.git "$(orbit env ORBIT_HOME)/profiles/hyperspace-labs"
          pip install -r "$(orbit env ORBIT_HOME)/profiles/hyperspace-labs/requirements.txt"
          orbit config --append include="profiles/hyperspace-labs/config.toml"

      - name: Verify prelude package has latest changes
        run: |
          python ./scripts/prelude.py

      - name: Perform static analysis
        run: |
          orbit b --target gsim --all -- --lint --std=93
          orbit b --target gsim --all -- --lint --std=02
          orbit b --target gsim --all -- --lint --std=08

      - name: Test types package
        run: |
          orbit t --target gsim --tb types_tb -- --std=93
          orbit t --target gsim --tb types_tb -- --std=02
          orbit t --target gsim --tb types_tb -- --std=08

      - name: Test math package
        run: |
          orbit t --target gsim --tb math_tb -- --std=93
          orbit t --target gsim --tb math_tb -- --std=02
          orbit t --target gsim --tb math_tb -- --std=08

      - name: Test manip package
        run: |
          orbit t --target gsim --tb manip_tb -- --std=93
          orbit t --target gsim --tb manip_tb -- --std=02
          orbit t --target gsim --tb manip_tb -- --std=08

      - name: Test dims package
        run: |
          orbit t --target gsim --tb dims_tb -- --std=93
          orbit t --target gsim --tb dims_tb -- --std=02
          orbit t --target gsim --tb dims_tb -- --std=08

      - name: Test cast package
        run: |
          orbit t --target gsim --tb cast_tb -- --std=93
          orbit t --target gsim --tb cast_tb -- --std=02
          orbit t --target gsim --tb cast_tb -- --std=08